name: safe
description: A powerful tool for personal and community safety.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.3
  flutter_svg: ^1.1.1+1
  flutter_linkify: ^5.0.2
  provider: ^6.0.3
  uuid: ^3.0.6
  battery_plus: ^2.1.4
  sliding_up_panel: ^2.0.0+1
  animations: ^2.0.3
  url_launcher: ^6.1.4
  http: ^0.13.4
  phone_number: ^0.12.0+2
  logger: ^1.1.0
  connectivity_plus: ^2.3.5
  cron: ^0.5.0
  permission_handler: ^10.0.0
  cached_network_image: ^3.2.1
  flutter_native_splash: ^2.2.3+1
  local_auth: ^2.1.0
  mobx: ^2.0.7+4
  camera: ^0.9.8+1
  flutter_mobx: ^2.0.6+1
  emojis: ^0.9.9
  shimmer: ^2.0.0
  agora_rtc_engine: ^6.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  dotted_border: ^2.0.0+2
  animated_text_kit: ^4.2.2
  card_swiper: ^2.0.4
  rive: ^0.9.0
  location: ^4.4.0
  flip_card: ^0.6.0
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.5+3
  flutter_local_notifications: ^9.6.1
  figma_squircle: ^0.5.3
  cloud_firestore: ^4.2.0
  pin_code_fields: ^7.4.0
  firebase_storage: ^11.0.7
  flutter_inset_box_shadow: ^1.0.8
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  share_plus: ^4.0.10
  firebase_app_check: ^0.1.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^2.0.7
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#070508"
  image: assets/images/splash.png

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svgs/logo.svg
    - assets/animations/bubbles.riv
    - assets/svgs/button.svg
    - assets/images/
    - assets/images/welcome/
    - assets/map/style.txt

  fonts:
    # SF Pro Rounded
    - family: RoundedBlack
      fonts:
        - asset: assets/fonts/rounded/SF-Pro-Rounded-Black.ttf
    - family: RoundedBold
      fonts:
        - asset: assets/fonts/rounded/SF-Pro-Rounded-Bold.ttf
    - family: RoundedHeavy
      fonts:
        - asset: assets/fonts/rounded/SF-Pro-Rounded-Heavy.ttf
    - family: RoundedLight
      fonts:
        - asset: assets/fonts/rounded/SF-Pro-Rounded-Light.ttf
    - family: RoundedRegular
      fonts:
        - asset: assets/fonts/rounded/SF-Pro-Rounded-Regular.ttf
    - family: RoundedSemibold
      fonts:
        - asset: assets/fonts/rounded/SF-Pro-Rounded-Semibold.ttf
    - family: RoundedThin
      fonts:
        - asset: assets/fonts/rounded/SF-Pro-Rounded-Thin.ttf
    - family: RoundedUltralight
      fonts:
        - asset: assets/fonts/rounded/SF-Pro-Rounded-Ultralight.ttf
    - family: RoundedMedium
      fonts:
        - asset: assets/fonts/rounded/SF-Pro-Rounded-Medium.ttf
