class CountryCodeUtil {
  Map<String, String> countryCodes = {
    "Albania": "355",
    "Algeria": "213",
    "Andorra": "376",
    "Angola": "244",
    "Antartica": "672",
    "Argentina": "54",
    "Armenia": "374",
    "Aruba": "297",
    "Australia": "61",
    "Austria": "43",
    "Bahrain": "973",
    "Bagladesh": "880",
    "Belarus": "375",
    "Belgium": "32",
    "Belize": "501",
    "Benin": "221",
    "Bhutan": "975",
    "Bolivia": "591",
    "Bosnia and Herzegovina": "387",
    "Botswana": "267",
    "Brazil": "55",
    "British Indian Ocean Territory": "246",
    "Brunei": "673",
    "Bulgaria": "359",
    "Burkina Faso": "226",
    "Burundi": "257",
    "Cambodia": "885",
    "Cameroon": "237",
    "Canada": "1",
    "Cape verde": "238",
    "Central African Republic": "236",
    "Chad": "235",
    "China": "86",
    "Chile": "56",
    "Christmas Island": "61",
    "Cocos Islands": "61",
    "Colombia": "57",
    "Comoros": "269",
    "Cook Islands": "682",
    "Costa Rica": "506",
    "Croatia": "385",
    "Cuba": "53",
    "Cucaro": "599",
    "Cyprus": "357",
    "Czech Republic": "420",
    "Democratic Republic of the Congo": "243",
    "Denmark": "45",
    "Djibouti": "253",
    "East Timor": "670",
    "Ecuador": "593",
    "Egypt": "20",
    "El Salvador": "503",
    "Equatorial Guinea": "240",
    "Eritrea": "291",
    "Estonia": "372",
    "Ethiopia": "251",
    "Falkland Islands": "500",
    "Faroe Islands": "298",
    "Fiji": "679",
    "Finland": "358",
    "France": "33",
    "French Polynesia": "689",
    "Gabon": "241",
    "Gambia": "220",
    "Georgia": "995",
    "Germany": "49",
    "Ghana": "233",
    "Gibraltar": "350",
    "Greece": "30",
    "Greenland": "229",
    "Guatemala": "502",
    "Guinea": "224",
    "Guinea-Bissau": "245",
    "Guyana": "592",
    "Haiti": "509",
    "Honduras": "504",
    "Hong Kong": "852",
    "Hungary": "36",
    "Iceland": "354",
    "India": "91",
    "Indonesia": "62",
    "Ireland": "353",
    "Israel": "972",
    "Italy": "39",
    "Japan": "81",
    "Jordan": "962",
    "Kazakhstan": "7",
    "Kenya": "254",
    "Kiribati": "686",
    "Kosovo": "383",
    "Kuwait": "965",
    "Kyrgyzstan": "996",
    "Laos": "856",
    "Latvia": "371",
    "Lebanon": "961",
    "Lesotho": "266",
    "Liberia": "231",
    "Libya": "218",
    "Lithuania": "370",
    "Luxembourg": "352",
    "Macau": "853",
    "Macedonia": "389",
    "Madagascar": "261",
    "Malawi": "265",
    "Malaysia": "60",
    "Maldives": "960",
    "Mali": "223",
    "Malta": "356",
    "Marshall Islands": "692",
    "Mexico": "52",
    "Micronesia": "691",
    "Moldova": "373",
    "Monaco": "377",
    "Mongolia": "976",
    "Montenegro": "382",
    "Morocco": "212",
    "Mozambique": "258",
    "Myanmar": "95",
    "Nepal": "977",
    "Netherlands": "31",
    "Netherlands Antilles": "599",
    "New Caledonia": "687",
    "New Zealand": "64",
    "Nicaragua": "505",
    "Niger": "227",
    "Nigeria": "234",
    "Niue": "683",
    "Norway": "47",
    "Oman": "968",
    "Palau": "680",
    "Palestine": "970",
    "Panama": "507",
    "Papua New Guinea": "675",
    "Paraguay": "595",
    "Peru": "51",
    "Philippines": "63",
    "Pitcairn": "64",
    "Poland": "48",
    "Portugal": "351",
    "Quatar": "974",
    "Republic of the Congo": "242",
    "Reunion": "262",
    "Romania": "40",
    "Russia": "7",
    "Rwanda": "250",
    "Saudi Arabia": "966",
    "Serbia": "381",
    "Singapore": "65",
    "Slovakia": "421",
    "Slovenia": "386",
    "Somalia": "252",
    "South Africa": "27",
    "South Korea": "82",
    "South Sudan": "211",
    "Spain": "34",
    "Sri Lanka": "94",
    "Sudan": "249",
    "Sweden": "46",
    "Switzerland": "41",
    "Taiwan": "886",
    "Tanzania": "255",
    "Thailand": "66",
    "Turkey": "90",
    "Uganda": "256",
    "Ukraine": "380",
    "United Arab Emirates": "971",
    "United Kingdom": "44",
    "United States": "1",
    "Uruguay": "598",
    "Venezuela": "58",
    "Vietnam": "84",
    "Yemen": "967",
    "Zambia": "260",
    "Zimbabwe": "263",
  };

  List<Map<String, String>> display() {
    List<Map<String, String>> result = [];

    for (String country in countryCodes.keys.toList()) {
      result.add({
        "name": country,
        "code": countryCodes[country]!,
      });
    }

    return result;
  }

  List<Map<String, String>> search(String query) {
    List<Map<String, String>> result = [];

    for (String country in countryCodes.keys.toList()) {
      String lowecase = country.toLowerCase().substring(
            0,
            country.length < query.length ? country.length : query.length,
          );

      if (lowecase.contains(query.toLowerCase())) {
        result.add({
          "name": country,
          "code": countryCodes[country]!,
        });
      }
    }

    return result;
  }
}
